name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t amkura/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push amkura/expiration
      - uses: digitalocean/action-doctl@v2 # installs doctl into git
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }} # using this for authorization
      - run: doctl kubernetes cluster kubeconfig save tickets # reaching into the cluster
      - run: kubectl rollout restart deployment expiration-depl # reaching into the cluster to restart
