name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2 # installs doctl into git
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }} # using this for authorization
      - run: doctl kubernetes cluster kubeconfig save tickets # reaching into the cluster
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod # applies all the config files to our cluster
