name: tests-orders

on:
  pull_request:
    paths: # if there's ever a pull request, run jobs only if changes are inside auth directory
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm i && npm run test:ci
